version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-all:
        patterns:
          - "*"
        update-types:
          - major
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-all:
        patterns:
          - "*"
        update-types:
          - major
          - minor
          - patch

  - package-ecosystem: docker
    directory: /infra/docker
    schedule:
      interval: weekly
    groups:
      docker-all:
        patterns:
          - "*"
        update-types:
          - major
          - minor
          - patch

  - package-ecosystem: docker
    directory: /infra/k8s/k8s-with-external-db
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /infra/k8s/k8s-with-internal-db
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /infra/k8s/k8s-with-replicas-and-external-db
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /infra/k8s/k8s-with-replicas-and-internal-ha-db
    schedule:
      interval: weekly
